AllCops:
  TargetRubyVersion: 2.5

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: False

Metrics/MethodLength:
  Enabled: False

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/ParallelAssignment:
  Enabled: False
